import { ApolloClient, InMemoryCache } from '@apollo/client';

// generated by Fragment Matcher plugin
import introspectionResult from './introspection-result';

// Utilize the environment variables defined in the `.env` file
const {
  REACT_APP_CONTENTFUL_SPACE_ID: SPACE_ID,
  REACT_APP_CONTENTFUL_ENVIRONMENT: ENVIRONMENT,
  REACT_APP_CONTENTFUL_API_KEY: API_KEY,
} = process.env;

const CONTENTFUL_GRAPHQL_ENDPOINT = `https://graphql.contentful.com/content/v1/spaces/${SPACE_ID}/environments/${ENVIRONMENT}`;

const apolloClient = new ApolloClient({
  uri: CONTENTFUL_GRAPHQL_ENDPOINT,
  headers: {
    Authorization: `Bearer ${API_KEY}`,
  },
  cache: new InMemoryCache({
    possibleTypes: introspectionResult.possibleTypes,
  }),
});

export {
  apolloClient,
  SPACE_ID,
  ENVIRONMENT,
  API_KEY,
  CONTENTFUL_GRAPHQL_ENDPOINT,
}
