import { ApolloClient, InMemoryCache, defaultDataIdFromObject } from '@apollo/client';

// generated by Fragment Matcher plugin
import introspectionResult from './introspection-result';

// Mock support for multiple languages and translations via i18next
const mockI18nInstance = {
  language: 'en',
};

// Utilize the environment variables defined in the `.env` file
const {
  REACT_APP_CONTENTFUL_SPACE_ID: SPACE_ID,
  REACT_APP_CONTENTFUL_ENVIRONMENT: ENVIRONMENT,
  REACT_APP_CONTENTFUL_API_KEY: API_KEY,
} = process.env;

const CONTENTFUL_GRAPHQL_ENDPOINT = `https://graphql.contentful.com/content/v1/spaces/${SPACE_ID}/environments/${ENVIRONMENT}`;

const apolloClient = new ApolloClient({
  uri: CONTENTFUL_GRAPHQL_ENDPOINT,
  headers: {
    Authorization: `Bearer ${API_KEY}`,
  },
  cache: new InMemoryCache({
    possibleTypes: introspectionResult.possibleTypes,
    dataIdFromObject: (obj) => {
      if (obj.sys) {
        if ((obj.sys as any).id) {
          return `${obj.__typename}_${mockI18nInstance.language}:${(obj.sys as any).id}`;
        } else if (process.env.NODE_ENV === 'development') {
          throw new Error(`Unable to cache ${obj.__typename} because sys.id was not fetched`);
        }
      }

      if (obj.__typename === 'Sys') {
        return;
      }

      return defaultDataIdFromObject(obj);
    },
  }),
});

export {
  apolloClient,
  SPACE_ID,
  ENVIRONMENT,
  API_KEY,
  CONTENTFUL_GRAPHQL_ENDPOINT,
}
